title: Hack the Beach
url: "http://thekaveman.github.io/hackthebeach"
baseurl: ""

email: data@smgov.net
github_username: CityofSantaMonica

collections:
  agendas:
    defaults:
      layout: agenda
