- name: GIS
  url: https://github.com/CityofSantaMonica/GIS
  description: Static and historic data layers in multiple formats.
  icon: fa-globe

- name: GTFS Real Time
  url: https://github.com/CityofSantaMonica/GTFS
  description: Big Blue Bus real-time position and trip updates.
  icon: fa-clock-o

- name: GTFS Static
  url: https://github.com/CityofSantaMonica/GTFS
  description: Big Blue Bus current and historic schedule information.
  icon: fa-bus

- name: Parking Meters
  url: https://parking.api.smgov.net
  description: Near real-time feed of on-street parking meter activity.
  icon: fa-tachometer

- name: Socrata Open Data Portal
  url: https://data.smgov.net/browse
  description: Be sure to check out the Transportation category.
  icon: fa-table
